name: bluebus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  geolocator: ^13.0.1
  http: ^1.4.0
  provider: ^6.0.0
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2 
  flutter_email_sender: ^7.0.0
  haptic_feedback: ^0.5.1+1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/urbanist/static/Urbanist-Thin.ttf
          weight: 100
        - asset: fonts/urbanist/static/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: fonts/urbanist/static/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/urbanist/static/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/urbanist/static/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/urbanist/static/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/urbanist/static/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/urbanist/static/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/urbanist/static/Urbanist-Black.ttf
          weight: 900
        - asset: fonts/urbanist/Urbanist-Italic-VariableFont_wght.ttf
          style: italic
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21